# Generated by Django 6.0.6 on 2026-06-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Categories",
            new_name="Category",
        ),
    ]
